/**
 * Gitignore Template Management
 * Manage .gitignore templates for different project types
 */

import * as fs from 'fs/promises';
import * as path from 'path';
import * as os from 'os';

export interface GitignoreTemplate {
  name: string;
  description: string;
  patterns: string[];
}

export const defaultTemplates: Record<string, GitignoreTemplate> = {
  node: {
    name: 'Node.js',
    description: 'Common Node.js patterns',
    patterns: [
      'node_modules/',
      'npm-debug.log*',
      'yarn-debug.log*',
      'yarn-error.log*',
      '.npm',
      '.yarn-integrity',
      'dist/',
      'build/',
      '*.tgz',
    ],
  },
  typescript: {
    name: 'TypeScript',
    description: 'TypeScript compilation artifacts',
    patterns: ['*.tsbuildinfo', 'dist/', 'build/', '*.js', '*.js.map', '*.d.ts'],
  },
  python: {
    name: 'Python',
    description: 'Python bytecode and virtual environments',
    patterns: ['__pycache__/', '*.py[cod]', '*$py.class', '.Python', 'venv/', 'ENV/', '*.egg-info/', 'dist/', 'build/'],
  },
  secrets: {
    name: 'Secrets',
    description: 'Sensitive files that should never be committed',
    patterns: ['.env', '.env.local', '.env.*.local', '*.pem', '*.key', 'secrets/', 'credentials.json'],
  },
  macos: {
    name: 'macOS',
    description: 'macOS system files',
    patterns: ['.DS_Store', '.AppleDouble', '._*'],
  },
  windows: {
    name: 'Windows',
    description: 'Windows system files',
    patterns: ['Thumbs.db', 'Desktop.ini'],
  },
};

export const gitignoreManager = {
  templatesDir: path.join(os.homedir(), '.gitconnect', 'gitignore-templates'),

  getTemplate(name: string): GitignoreTemplate | null {
    return defaultTemplates[name] || null;
  },

  listTemplates(): GitignoreTemplate[] {
    return Object.values(defaultTemplates);
  },

  generateGitignore(templateNames: string[]): string {
    const patterns = new Set<string>();
    const headers: string[] = [];

    for (const name of templateNames) {
      const template = this.getTemplate(name);
      if (template) {
        headers.push(`# ${template.name}`);
        for (const pattern of template.patterns) {
          patterns.add(pattern);
        }
      }
    }

    return ['# Generated by GitConnect', '', ...headers, '', ...Array.from(patterns).sort(), ''].join('\n');
  },

  async writeGitignore(targetDir: string, templateNames: string[]): Promise<boolean> {
    try {
      const content = this.generateGitignore(templateNames);
      await fs.writeFile(path.join(targetDir, '.gitignore'), content, 'utf-8');
      return true;
    } catch {
      return false;
    }
  },

  async readGitignore(targetDir: string): Promise<string[]> {
    try {
      const content = await fs.readFile(path.join(targetDir, '.gitignore'), 'utf-8');
      return content.split('\n').filter(line => line.trim() && !line.startsWith('#'));
    } catch {
      return [];
    }
  },
};