/**
 * Bash completion script generator for GitConnect
 */

import { ConfigManager } from '../core/config';

export async function generateBashCompletion(): Promise<string> {
  const config = new ConfigManager();
  let accounts: string[] = [];

  try {
    if (await config.isInitialized()) {
      const accountList = await config.getAccounts();
      accounts = accountList.map(a => a.username);
    }
  } catch {
    // Config not initialized, use empty accounts list
  }

  // Using string concatenation to avoid TypeScript interpreting shell variables
  const script = `# Bash completion for gitconnect / gc
# Generated by GitConnect

_gitconnect() {
    local cur prev words cword
    _init_completion || return

    local commands="init account project commit push use status hooks completion install-hook uninstall-hook"
    local account_actions="add list remove"
    local project_actions="set mode info"
    local hooks_actions="install uninstall status mode silent"
    local modes="auto prompt off"
    local hook_types="commit push all"
    local silent_values="on off"
    local shells="bash zsh fish"
    local completion_actions="install uninstall \${shells}"

    # Account names for dynamic completion
    local accounts="${accounts.join(' ')}"

    case \${prev} in
        gitconnect|gc)
            COMPREPLY=($(compgen -W "\${commands}" -- "\${cur}"))
            return
            ;;
        account)
            COMPREPLY=($(compgen -W "\${account_actions}" -- "\${cur}"))
            return
            ;;
        project)
            COMPREPLY=($(compgen -W "\${project_actions}" -- "\${cur}"))
            return
            ;;
        hooks)
            COMPREPLY=($(compgen -W "\${hooks_actions}" -- "\${cur}"))
            return
            ;;
        completion)
            COMPREPLY=($(compgen -W "\${completion_actions}" -- "\${cur}"))
            return
            ;;
        use)
            COMPREPLY=($(compgen -W "\${accounts}" -- "\${cur}"))
            return
            ;;
        remove)
            COMPREPLY=($(compgen -W "\${accounts}" -- "\${cur}"))
            return
            ;;
        mode)
            COMPREPLY=($(compgen -W "\${modes}" -- "\${cur}"))
            return
            ;;
        silent)
            COMPREPLY=($(compgen -W "\${silent_values}" -- "\${cur}"))
            return
            ;;
        -t|--type)
            COMPREPLY=($(compgen -W "\${hook_types}" -- "\${cur}"))
            return
            ;;
        -a|--account)
            COMPREPLY=($(compgen -W "\${accounts}" -- "\${cur}"))
            return
            ;;
    esac

    # Option completion
    if [[ \${cur} == -* ]]; then
        case \${prev} in
            commit)
                COMPREPLY=($(compgen -W "-m --message --amend -s --sign -a --account --help" -- "\${cur}"))
                return
                ;;
            push)
                COMPREPLY=($(compgen -W "-a --account --auto --help" -- "\${cur}"))
                return
                ;;
            hooks)
                COMPREPLY=($(compgen -W "-t --type --help" -- "\${cur}"))
                return
                ;;
        esac
    fi
}

# Register for both gitconnect and gc (alias)
complete -F _gitconnect gitconnect
complete -F _gitconnect gc
`;

  return script;
}