/**
 * Fish completion script generator for GitConnect
 */

import { ConfigManager } from '../core/config';

export async function generateFishCompletion(): Promise<string> {
  const config = new ConfigManager();
  let accounts: Array<{ username: string; email: string }> = [];

  try {
    if (await config.isInitialized()) {
      accounts = await config.getAccounts();
    }
  } catch {
    // Config not initialized, use empty accounts list
  }

  const accountCompletions = accounts.map(a =>
    `complete -c gitconnect -n '__fish_seen_subcommand_from use' -a '${a.username}' -d '${a.email}'`
  ).join('\n');

  const removeAccountCompletions = accounts.map(a =>
    `complete -c gitconnect -n '__fish_seen_subcommand_from account; and __fish_seen_subcommand_from remove' -a '${a.username}' -d '${a.email}'`
  ).join('\n');

  return `# Fish completion for GitConnect
# Generated by GitConnect

# Disable file completion by default
complete -c gitconnect -f

# Main commands
complete -c gitconnect -n '__fish_use_subcommand' -a init -d 'Initialize GitConnect configuration'
complete -c gitconnect -n '__fish_use_subcommand' -a account -d 'Manage GitHub accounts'
complete -c gitconnect -n '__fish_use_subcommand' -a project -d 'Manage project settings'
complete -c gitconnect -n '__fish_use_subcommand' -a commit -d 'Commit with GitConnect'
complete -c gitconnect -n '__fish_use_subcommand' -a push -d 'Push with GitConnect'
complete -c gitconnect -n '__fish_use_subcommand' -a use -d 'Use account for this shell session'
complete -c gitconnect -n '__fish_use_subcommand' -a status -d 'Show GitConnect status'
complete -c gitconnect -n '__fish_use_subcommand' -a hooks -d 'Manage git hooks'
complete -c gitconnect -n '__fish_use_subcommand' -a completion -d 'Generate shell completion scripts'
complete -c gitconnect -n '__fish_use_subcommand' -a install-hook -d 'Install git push hook (legacy)'
complete -c gitconnect -n '__fish_use_subcommand' -a uninstall-hook -d 'Uninstall git push hook (legacy)'

# Alias 'gc'
complete -c gc -w gitconnect

# Account subcommands
complete -c gitconnect -n '__fish_seen_subcommand_from account; and not __fish_seen_subcommand_from add list remove' -a add -d 'Add a new GitHub account'
complete -c gitconnect -n '__fish_seen_subcommand_from account; and not __fish_seen_subcommand_from add list remove' -a list -d 'List all accounts'
complete -c gitconnect -n '__fish_seen_subcommand_from account; and not __fish_seen_subcommand_from add list remove' -a remove -d 'Remove an account'

# Project subcommands
complete -c gitconnect -n '__fish_seen_subcommand_from project; and not __fish_seen_subcommand_from set mode info' -a set -d 'Set account for current project'
complete -c gitconnect -n '__fish_seen_subcommand_from project; and not __fish_seen_subcommand_from set mode info' -a mode -d 'Set project mode'
complete -c gitconnect -n '__fish_seen_subcommand_from project; and not __fish_seen_subcommand_from set mode info' -a info -d 'Show current project info'

# Mode values
complete -c gitconnect -n '__fish_seen_subcommand_from project; and __fish_seen_subcommand_from mode' -a auto -d 'Use configured account automatically'
complete -c gitconnect -n '__fish_seen_subcommand_from project; and __fish_seen_subcommand_from mode' -a prompt -d 'Ask for account before each commit/push'
complete -c gitconnect -n '__fish_seen_subcommand_from project; and __fish_seen_subcommand_from mode' -a off -d 'Disable GitConnect hooks temporarily'

# Hooks subcommands
complete -c gitconnect -n '__fish_seen_subcommand_from hooks; and not __fish_seen_subcommand_from install uninstall status mode silent' -a install -d 'Install git hooks'
complete -c gitconnect -n '__fish_seen_subcommand_from hooks; and not __fish_seen_subcommand_from install uninstall status mode silent' -a uninstall -d 'Uninstall git hooks'
complete -c gitconnect -n '__fish_seen_subcommand_from hooks; and not __fish_seen_subcommand_from install uninstall status mode silent' -a status -d 'Show hook status'
complete -c gitconnect -n '__fish_seen_subcommand_from hooks; and not __fish_seen_subcommand_from install uninstall status mode silent' -a mode -d 'Set hook mode'
complete -c gitconnect -n '__fish_seen_subcommand_from hooks; and not __fish_seen_subcommand_from install uninstall status mode silent' -a silent -d 'Enable/disable silent mode'

# Hook type values
complete -c gitconnect -n '__fish_seen_subcommand_from hooks; and __fish_seen_subcommand_from install' -l type -d 'Hook type' -r -a "commit\\t'Pre-commit hook' push\\t'Pre-push hook' all\\t'Both hooks'"
complete -c gitconnect -n '__fish_seen_subcommand_from hooks; and __fish_seen_subcommand_from install' -s t -d 'Hook type' -r -a "commit\\t'Pre-commit hook' push\\t'Pre-push hook' all\\t'Both hooks'"

# Hook mode values
complete -c gitconnect -n '__fish_seen_subcommand_from hooks; and __fish_seen_subcommand_from mode' -a auto -d 'Use configured account automatically'
complete -c gitconnect -n '__fish_seen_subcommand_from hooks; and __fish_seen_subcommand_from mode' -a prompt -d 'Ask for account before each commit/push'
complete -c gitconnect -n '__fish_seen_subcommand_from hooks; and __fish_seen_subcommand_from mode' -a off -d 'Disable GitConnect hooks temporarily'

# Silent mode values
complete -c gitconnect -n '__fish_seen_subcommand_from hooks; and __fish_seen_subcommand_from silent' -a on -d 'Enable silent mode'
complete -c gitconnect -n '__fish_seen_subcommand_from hooks; and __fish_seen_subcommand_from silent' -a off -d 'Disable silent mode'

# Completion subcommands
complete -c gitconnect -n '__fish_seen_subcommand_from completion; and not __fish_seen_subcommand_from install uninstall bash zsh fish' -a install -d 'Auto-install completions'
complete -c gitconnect -n '__fish_seen_subcommand_from completion; and not __fish_seen_subcommand_from install uninstall bash zsh fish' -a uninstall -d 'Remove installed completions'
complete -c gitconnect -n '__fish_seen_subcommand_from completion; and not __fish_seen_subcommand_from install uninstall bash zsh fish' -a bash -d 'Output bash completion'
complete -c gitconnect -n '__fish_seen_subcommand_from completion; and not __fish_seen_subcommand_from install uninstall bash zsh fish' -a zsh -d 'Output zsh completion'
complete -c gitconnect -n '__fish_seen_subcommand_from completion; and not __fish_seen_subcommand_from install uninstall bash zsh fish' -a fish -d 'Output fish completion'

# Commit options
complete -c gitconnect -n '__fish_seen_subcommand_from commit' -l message -d 'Commit message' -r
complete -c gitconnect -n '__fish_seen_subcommand_from commit' -s m -d 'Commit message' -r
complete -c gitconnect -n '__fish_seen_subcommand_from commit' -l amend -d 'Amend previous commit'
complete -c gitconnect -n '__fish_seen_subcommand_from commit' -l sign -d 'Sign commit with SSH key'
complete -c gitconnect -n '__fish_seen_subcommand_from commit' -s s -d 'Sign commit with SSH key'
complete -c gitconnect -n '__fish_seen_subcommand_from commit' -l account -d 'Use specific account' -r
complete -c gitconnect -n '__fish_seen_subcommand_from commit' -s a -d 'Use specific account' -r

# Push options
complete -c gitconnect -n '__fish_seen_subcommand_from push' -l account -d 'Use specific account' -r
complete -c gitconnect -n '__fish_seen_subcommand_from push' -s a -d 'Use specific account' -r
complete -c gitconnect -n '__fish_seen_subcommand_from push' -l auto -d 'Use auto mode (non-interactive)'

# Dynamic account completions for 'use'
${accountCompletions || '# No accounts configured'}

# Dynamic account completions for 'account remove'
${removeAccountCompletions || '# No accounts configured'}
`;
}