/**
 * Zsh completion script generator for GitConnect
 */

import { ConfigManager } from '../core/config';

export async function generateZshCompletion(): Promise<string> {
  const config = new ConfigManager();
  let accounts: string[] = [];

  try {
    if (await config.isInitialized()) {
      const accountList = await config.getAccounts();
      accounts = accountList.map(a => a.username);
    }
  } catch {
    // Config not initialized, use empty accounts list
  }

  const accountsStr = accounts.length > 0
    ? `'(${accounts.join(' ')})'`
    : '\'()\'';

  // Using string concatenation to avoid TypeScript interpreting shell variables
  const script = `#compdef gitconnect gc
# Zsh completion for GitConnect
# Generated by GitConnect

_gitconnect() {
    local -a commands
    commands=(
        'init:Initialize GitConnect configuration'
        'account:Manage GitHub accounts'
        'project:Manage project settings'
        'commit:Commit with GitConnect (prompts for account)'
        'push:Push with GitConnect (explicit mode)'
        'use:Use account for this shell session'
        'status:Show GitConnect status'
        'hooks:Manage git hooks'
        'completion:Generate shell completion scripts'
        'install-hook:Install git push hook (legacy)'
        'uninstall-hook:Uninstall git push hook (legacy)'
    )

    local -a account_actions
    account_actions=(
        'add:Add a new GitHub account'
        'list:List all accounts'
        'remove:Remove an account'
    )

    local -a project_actions
    project_actions=(
        'set:Set account for current project'
        'mode:Set project mode (auto/prompt)'
        'info:Show current project info'
    )

    local -a hooks_actions
    hooks_actions=(
        'install:Install git hooks'
        'uninstall:Uninstall git hooks'
        'status:Show hook status'
        'mode:Set hook mode (prompt/auto/off)'
        'silent:Enable/disable silent mode (on/off)'
    )

    local -a modes
    modes=(
        'auto:Use configured account automatically'
        'prompt:Ask for account before each commit/push'
        'off:Disable GitConnect hooks temporarily'
    )

    local -a hook_types
    hook_types=(
        'commit:Pre-commit hook'
        'push:Pre-push hook'
        'all:Both hooks'
    )

    local -a shells
    shells=(
        'bash:Bash completion'
        'zsh:Zsh completion'
        'fish:Fish completion'
    )

    local -a completion_actions
    completion_actions=(
        'install:Auto-install completions for current shell'
        'uninstall:Remove installed completions'
        'bash:Output bash completion script'
        'zsh:Output zsh completion script'
        'fish:Output fish completion script'
    )

    # Account names from config
    local -a accounts
    accounts=${accountsStr}

    _arguments -C \\
        '1: :->command' \\
        '*: :->args'

    case $state in
        command)
            _describe 'command' commands
            ;;
        args)
            case \${words[2]} in
                account)
                    case \${words[3]} in
                        remove)
                            _describe 'account' accounts
                            ;;
                        *)
                            if [[ $CURRENT -eq 3 ]]; then
                                _describe 'action' account_actions
                            fi
                            ;;
                    esac
                    ;;
                project)
                    if [[ $CURRENT -eq 3 ]]; then
                        _describe 'action' project_actions
                    elif [[ \${words[3]} == 'mode' ]]; then
                        _describe 'mode' modes
                    fi
                    ;;
                hooks)
                    if [[ $CURRENT -eq 3 ]]; then
                        _describe 'action' hooks_actions
                    elif [[ \${words[3]} == 'mode' ]]; then
                        _describe 'mode' modes
                    elif [[ \${words[3]} == 'silent' ]]; then
                        _values 'silent' 'on[Enable silent mode]' 'off[Disable silent mode]'
                    elif [[ \${words[3]} == 'install' || \${words[3]} == 'uninstall' ]]; then
                        _values 'type' 'commit[Pre-commit hook]' 'push[Pre-push hook]' 'all[Both hooks]'
                    fi
                    ;;
                completion)
                    if [[ $CURRENT -eq 3 ]]; then
                        _describe 'action' completion_actions
                    fi
                    ;;
                use)
                    _describe 'account' accounts
                    ;;
                commit)
                    _arguments \\
                        '-m[Commit message]:message:' \\
                        '--message[Commit message]:message:' \\
                        '--amend[Amend previous commit]' \\
                        '-s[Sign commit with SSH key]' \\
                        '--sign[Sign commit with SSH key]' \\
                        '-a[Use specific account]:account:' \\
                        '--account[Use specific account]:account:'
                    ;;
                push)
                    _arguments \\
                        '-a[Use specific account]:account:' \\
                        '--account[Use specific account]:account:' \\
                        '--auto[Use auto mode (non-interactive)]'
                    ;;
            esac
            ;;
    esac
}

_gitconnect
`;

  return script;
}